palette = "matugen"
format = """
[░▒▓](shadow)\
$os\
[](bg:primary fg:shadow)\
$directory\
[ ](fg:primary bg:surface_variant)\
$git_branch\
$git_status\
$hg_branch\
[ ](fg:surface_variant bg:shadow)\
[▓▒░](shadow)\
[ ◦•](outline)\
$fill\
[•◦ ](outline)\
[░▒▓](shadow)\
[ ](fg:surface_variant bg:shadow)\
$status\
$cmd_duration\
[ ](fg:shadow bg:surface_variant)\
$battery\
[▓▒░](shadow)
[·](surface_variant)\
[·](outline)\
[•](on_surface_variant)\
[ ](tertiary)\
"""

[fill]
symbol = "·"
style = "outline"

[directory]
style = "fg:surface_variant bg:primary"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"~" = "  "
"Applications" = "  "
"Desktop" = "  "
"Developer" = "  "
"Documents" = " 󰈙 "
"Downloads" = "  "
"Games" = "  "
"GitHub" = "  "
"Library" = "  "
"Movies" = "  "
"Music" = "  "
"Pictures" = "  "
"Projects" = "  "
"Public" = "  "
"Screenshots" = " 󱣴 "
"Videos" = "  "
"Thunderbird" = "   "
"source" = " 󰈹 "
"comm" = "  "

[git_branch]
symbol = ""
style = "bg:surface_variant"
format = '[[ $symbol $branch ](fg:primary bg:surface_variant)]($style)'

[git_status]
style = "bg:surface_variant"
format = '[[($all_status$ahead_behind )](fg:primary bg:surface_variant)]($style)'

[hg_branch]
disabled = false
symbol = ""
style = "bg:surface_variant"
format = '[[ $symbol $branch ](fg:primary bg:surface_variant)]($style)'

[cmd_duration]
disabled = false
min_time = 0
show_milliseconds = true
style = "fg:on_surface bg:surface_variant"
format = '[$duration]($style)'

[status]
symbol = '  '
success_symbol = '  '
not_executable_symbol = '  '
not_found_symbol = '  '
map_symbol = true
disabled = false
style = 'fg:on_surface bg:surface_variant'
format = '[$symbol]($style)'

[os]
format = '[ $symbol]($style)'
style = 'fg:primary bg:shadow'
disabled = false

[os.symbols]
Arch = " "
CachyOS = " "
Debian = " "
Fedora = " "
FreeBSD = " "
Linux = " "
Macos = " "
NixOS = "󱄅 "
Nobara = " "
Pop = " "
Raspbian = " "
Ubuntu = " "
Unknown = " "

[palettes.matugen]
error = '{{colors.error.default.hex}}'
hover = '{{colors.hover.default.hex}}'
on_error = '{{colors.on_error.default.hex}}'
on_hover = '{{colors.on_hover.default.hex}}'
on_primary = '{{colors.on_primary.default.hex}}'
on_secondary = '{{colors.on_secondary.default.hex}}'
on_surface = '{{colors.on_surface.default.hex}}'
on_surface_variant = '{{colors.on_surface_variant.default.hex}}'
on_tertiary = '{{colors.on_tertiary.default.hex}}'
outline = '{{colors.outline.default.hex}}'
primary = '{{colors.primary.default.hex}}'
secondary = '{{colors.secondary.default.hex}}'
shadow = '{{colors.shadow.default.hex}}'
surface = '{{colors.surface.default.hex}}'
surface_variant = '{{colors.surface_variant.default.hex}}'
tertiary = '{{colors.tertiary.default.hex}}'
