[config]

[templates]

# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

[templates.rmpc]
input_path = "~/.config/noctalia/templates/rmpc.ron"
output_path = "/home/alext/.config/rmpc/themes/current_theme.ron"
post_hook = "echo 'rmpc theme updated'"

[templates.starship]
input_path = "~/.config/noctalia/templates/starship.toml"
output_path = "/home/alext/.config/starship.toml"
post_hook = "echo 'starship theme updated'"

[templates.nvim-base16]
input_path = "~/.config/noctalia/templates/neovim.lua"
output_path = "~/.config/nvim/lua/matugen.lua"
post_hook = 'pkill -SIGUSR1 nvim'